services:
  infra:
    image: vanishvpn-infra
    build:
      context: ./infra
      dockerfile: Dockerfile
    env_file:
      - ./infra/.env
    volumes:
      - /app/node_modules
      - ./infra:/app
    expose:
      - 3000